controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_lucky_number:
    path: /lucky-number
    controller: App\Controller\LuckyController::number
info_app:
    path: /info
    controller: App\Controller\InfoController::info
